<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPRURYAW7112" ignored="0" name="TestsWithFactoryForCircle" tests="15" failures="6" timestamp="06 фев 2019 15:30:02 GMT" time="0.084" errors="0">
  <testcase name="testGetCircle" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetCircle" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetCircle" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetCircle" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetCircle" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetCircumference" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetCircumference" time="0.0" classname="jar.circle.TestsForCircle">
    <failure type="java.lang.AssertionError" message="expected [22.305] but found [140.146]">
      <![CDATA[java.lang.AssertionError: expected [22.305] but found [140.146]
at jar.circle.TestsForCircle.testGetCircumference(TestsForCircle.java:26)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGetCircumference -->
  <testcase name="testGetCircumference" time="0.0" classname="jar.circle.TestsForCircle">
    <failure type="java.lang.AssertionError" message="expected [-22.305] but found [140.146]">
      <![CDATA[java.lang.AssertionError: expected [-22.305] but found [140.146]
at jar.circle.TestsForCircle.testGetCircumference(TestsForCircle.java:26)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGetCircumference -->
  <testcase name="testGetCircumference" time="0.0" classname="jar.circle.TestsForCircle">
    <failure type="java.lang.AssertionError" message="expected [-18.85] but found [118.438]">
      <![CDATA[java.lang.AssertionError: expected [-18.85] but found [118.438]
at jar.circle.TestsForCircle.testGetCircumference(TestsForCircle.java:26)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGetCircumference -->
  <testcase name="testGetCircumference" time="0.0" classname="jar.circle.TestsForCircle">
    <failure type="java.lang.AssertionError" message="expected [18.85] but found [118.438]">
      <![CDATA[java.lang.AssertionError: expected [18.85] but found [118.438]
at jar.circle.TestsForCircle.testGetCircumference(TestsForCircle.java:26)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGetCircumference -->
  <testcase name="testGetSquare" time="0.007" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetSquare" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetSquare" time="0.0" classname="jar.circle.TestsForCircle">
    <failure type="java.lang.AssertionError" message="expected [39.592] but found [0.0]">
      <![CDATA[java.lang.AssertionError: expected [39.592] but found [0.0]
at jar.circle.TestsForCircle.testGetSquare(TestsForCircle.java:34)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGetSquare -->
  <testcase name="testGetSquare" time="0.0" classname="jar.circle.TestsForCircle">
    <failure type="java.lang.AssertionError" message="expected [28.274] but found [0.0]">
      <![CDATA[java.lang.AssertionError: expected [28.274] but found [0.0]
at jar.circle.TestsForCircle.testGetSquare(TestsForCircle.java:34)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGetSquare -->
  <testcase name="testGetSquare" time="0.0" classname="jar.circle.TestsForCircle"/>
</testsuite> <!-- TestsWithFactoryForCircle -->
